// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIn5tfcMWcJFDvomAXXi9gFP1cBroG_0k',
    appId: '1:141123971544:web:b4cd6649933febf5b3eaad',
    messagingSenderId: '141123971544',
    projectId: 'gilumn',
    authDomain: 'gilumn.firebaseapp.com',
    storageBucket: 'gilumn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA98BMhUOuxdVdwtbfOj3NxlNcfzWSmPbA',
    appId: '1:141123971544:android:951ab9ac4da45561b3eaad',
    messagingSenderId: '141123971544',
    projectId: 'gilumn',
    storageBucket: 'gilumn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF5AwwosmBNQFGxGhWmErrMA16jVqqU9I',
    appId: '1:141123971544:ios:906012591cbc69c3b3eaad',
    messagingSenderId: '141123971544',
    projectId: 'gilumn',
    storageBucket: 'gilumn.appspot.com',
    iosClientId: '141123971544-krm49o62icnc1kmauep722fdbbc6ueqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.gilumn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF5AwwosmBNQFGxGhWmErrMA16jVqqU9I',
    appId: '1:141123971544:ios:906012591cbc69c3b3eaad',
    messagingSenderId: '141123971544',
    projectId: 'gilumn',
    storageBucket: 'gilumn.appspot.com',
    iosClientId: '141123971544-krm49o62icnc1kmauep722fdbbc6ueqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.gilumn',
  );
}
